import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {once} from 'node:events';

test('coach and athlete lifecycle, authorization, calendar, deletion and redo',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'iron-heart-test-'));
  const child=spawn(process.execPath,['server/index.mjs','--test-server'],{env:{...process.env,PORT:'4185',DEMO_MODE:'true',DB_PATH:join(dir,'test.sqlite')},stdio:['ignore','pipe','pipe']});
  let output='';child.stdout.on('data',c=>output+=c);child.stderr.on('data',c=>output+=c);
  t.after(async()=>{const exit=once(child,'exit');child.kill();await exit;await rm(dir,{recursive:true,force:true});});
  for(let i=0;i<100&&!output.includes('Iron Heart Strength:');i++)await new Promise(r=>setTimeout(r,50));
  assert.ok(output.includes('Iron Heart Strength:'),output);
  const request=async(path,method='GET',body,token)=>{const r=await fetch('http://localhost:4185/api/'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
  assert.equal((await request('data')).status,401);
  const coach=(await request('demo','POST',{role:'coach',native:true})).data.token;
  const athlete=(await request('demo','POST',{role:'athlete',native:true})).data.token;
  const initial=(await request('data','GET',null,coach)).data;
  const athleteData=(await request('data','GET',null,athlete)).data;
  assert.equal(athleteData.programs.length,0);assert.equal(athleteData.athletes.length,0);assert.ok(athleteData.assignments.every(a=>a.athleteId==='jordan'));
  assert.equal((await request('programs','POST',initial.programs[0],athlete)).status,403);
  const template=structuredClone(initial.programs[0]);delete template.id;template.name='Integration test template';
  const created=await request('programs','POST',template,coach);assert.equal(created.status,200);const program=created.data;
  const assigned=await request('assign','POST',{programId:program.id,athleteId:'jordan',startDate:'2026-10-05'},coach);assert.equal(assigned.status,200);const a=assigned.data;
  const generated=structuredClone(program);
  generated.weeks=3;
  generated.plan=Array.from({length:3},(_,i)=>({week:i+1,sessions:structuredClone(generated.sessions)}));
  generated.plan[1].sessions[0].exercises[0].load=137.5;
  generated.plan[1].sessions[0].exercises[0].sets=12;
  assert.equal((await request('programs','POST',generated,coach)).status,200);
  const reloaded=(await request('data','GET',null,coach)).data.programs.find(x=>x.id===program.id);
  assert.equal(reloaded.plan[1].sessions[0].exercises[0].load,137.5);
  const personalized=(await request('assign','POST',{programId:program.id,athleteId:'maya',startDate:'2026-10-05'},coach)).data;
  assert.equal(personalized.plan[1].sessions[0].exercises[0].load,137.5);
  assert.equal(personalized.plan[1].sessions[0].exercises[0].sets,12);
  const invalid=structuredClone(generated);invalid.plan[2].sessions[0].exercises[0].load=-1;
  assert.equal((await request('programs','POST',invalid,coach)).status,400);
  const rows=structuredClone(a.plan[0].sessions[0].exercises);rows[0].load=22.5;
  const legacyMaximum=structuredClone(rows);legacyMaximum[0].load=1102.25;
  assert.equal((await request('assignment','PUT',{id:a.id,week:1,session:0,exercises:legacyMaximum},coach)).status,200);
  assert.equal((await request('assignment','PUT',{id:a.id,week:1,session:0,exercises:rows},coach)).status,200);
  assert.equal((await request('data','GET',null,coach)).data.programs.find(p=>p.id===program.id).sessions[0].exercises[0].load,template.sessions[0].exercises[0].load);
  assert.equal((await request('reschedule','POST',{id:a.id,week:1,session:0,day:2},coach)).data.plan[0].sessions[0].day,2);
  assert.equal((await request('reschedule','POST',{id:a.id,week:1,session:0,day:8},coach)).status,400);
  const payload={assignmentId:a.id,week:1,session:0,readiness:4,pain:false,notes:'Test session',exercises:rows.map(e=>({exerciseId:e.exerciseId,sets:Array.from({length:e.sets},()=>({load:e.load,reps:e.reps,rpe:7}))}))};
  const other=initial.assignments.find(x=>x.athleteId==='maya');
  assert.equal((await request('log','POST',{...payload,assignmentId:other.id},athlete)).status,403);
  assert.equal((await request('log','POST',{...payload,exercises:[]},athlete)).status,400);
  assert.equal((await request('session-status','POST',{id:a.id,week:1,session:0,cancelled:true},coach)).status,200);
  assert.equal((await request('log','POST',payload,athlete)).status,400);
  await request('session-status','POST',{id:a.id,week:1,session:0,cancelled:false},coach);
  const logged=await request('log','POST',payload,athlete);assert.equal(logged.status,200);
  assert.equal((await request('log','POST',payload,athlete)).status,409);
  assert.equal((await request('delete','POST',{kind:'log',id:logged.data.id},athlete)).status,200);
  assert.equal((await request('log','POST',payload,athlete)).status,200);
  assert.equal((await request('delete','POST',{kind:'assignment',id:a.id},athlete)).status,403);
  assert.equal((await request('delete','POST',{kind:'exercise',id:rows[0].exerciseId},coach)).status,409);
  assert.equal((await request('delete','POST',{kind:'program',id:program.id},coach)).status,200);
  assert.ok((await request('data','GET',null,coach)).data.assignments.some(x=>x.id===a.id));
  assert.equal((await request('delete','POST',{kind:'assignment',id:a.id},coach)).status,200);
  assert.ok((await request('data','GET',null,athlete)).data.logs.some(l=>l.assignmentId===a.id));
  const invitation=await request('athletes','POST',{name:'QA Athlete',email:'qa@example.test',sport:'Strength'},coach);assert.equal(invitation.status,200);
  assert.equal((await request('redeem','POST',{code:invitation.data.code,password:'short'})).status,400);
  const joined=await request('redeem','POST',{code:invitation.data.code,password:'test-only-password-123',native:true});assert.equal(joined.status,200);
  assert.equal((await request('redeem','POST',{code:invitation.data.code,password:'test-only-password-123'})).status,400);
  assert.equal((await request('delete','POST',{kind:'athlete',id:invitation.data.id},coach)).status,200);
  assert.equal((await request('data','GET',null,joined.data.token)).status,401);
});
