import test from 'node:test';
import assert from 'node:assert/strict';
import {createLocalDemo} from '../src/local-demo.mjs';
import {generateWestsideBlock} from '../server/progression.mjs';
const storage=()=>{const values=new Map();return {getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};};
test('phone preview persists pounds, generated weeks and manual edits independently of template',async()=>{
  const disk=storage(),api=createLocalDemo(disk);
  assert.equal((await api('config')).standalone,true);
  await api('demo','POST',{role:'coach'});
  const data=await api('data');assert.equal(data.programs[0].sessions[0].exercises[0].load,132.25);
  const p=data.programs[0];delete p.id;p.name='Phone program';
  p.plan=generateWestsideBlock(p.sessions,p.weeks,{rules:{'0:0:squat':{mode:'speed-squat',referenceMax:200}}});
  const saved=await api('programs','POST',p);
  const a=await api('assign','POST',{programId:saved.id,athleteId:'jordan',startDate:'2026-10-05'});
  assert.equal(a.plan[1].sessions[0].exercises[0].load,110);
  a.plan[1].sessions[0].exercises[0].load=105;
  await api('assignment','PUT',{id:a.id,week:2,session:0,exercises:a.plan[1].sessions[0].exercises});
  const reopened=await createLocalDemo(disk)('data');
  assert.equal(reopened.assignments.find(x=>x.id===a.id).plan[1].sessions[0].exercises[0].load,105);
  assert.equal(reopened.programs.find(x=>x.id===saved.id).plan[1].sessions[0].exercises[0].load,110);
  await api('delete','POST',{kind:'program',id:saved.id});
  assert.ok((await api('data')).assignments.some(x=>x.id===a.id));
});
test('phone preview logs, rejects duplicate, deletes and redoes; enforces athlete ownership',async()=>{
  const api=createLocalDemo(storage());await api('demo','POST',{role:'coach'});
  const other=(await api('data')).assignments.find(a=>a.athleteId==='maya');
  await api('demo','POST',{role:'athlete'});const d=await api('data');
  assert.equal(d.athletes.length,0);assert.ok(d.assignments.every(a=>a.athleteId==='jordan'));
  await assert.rejects(api('programs','POST',{name:'No'}),/Coach view/);
  await assert.rejects(api('log','POST',{assignmentId:other.id,week:1,session:0}),/not found/);
  const a=d.assignments[0],s=a.plan[0].sessions[0];
  const b={assignmentId:a.id,week:1,session:0,readiness:4,pain:false,notes:'Test',exercises:s.exercises.map(e=>({exerciseId:e.exerciseId,sets:Array.from({length:e.sets},()=>({load:e.load,reps:e.reps,rpe:7}))}))};
  const log=await api('log','POST',b);await assert.rejects(api('log','POST',b),/already logged/);
  await api('delete','POST',{kind:'log',id:log.id});await api('log','POST',b);
  assert.equal((await api('data')).logs.length,1);
});
test('phone preview calendar removal and restore persist; failed storage does not report success',async()=>{
  const disk=storage(),api=createLocalDemo(disk);await api('demo','POST',{role:'coach'});
  const a=(await api('data')).assignments[0];
  await api('reschedule','POST',{id:a.id,week:1,session:0,day:4});
  await api('session-status','POST',{id:a.id,week:1,session:0,cancelled:true});
  assert.equal((await api('data')).assignments[0].plan[0].sessions[0].cancelled,true);
  await api('session-status','POST',{id:a.id,week:1,session:0,cancelled:false});
  assert.equal((await createLocalDemo(disk)('data')).assignments[0].plan[0].sessions[0].day,4);
  const fail=createLocalDemo({getItem:disk.getItem,setItem:()=>{throw Error('Storage full');}});
  const validProgram=(await api('data')).programs[0];delete validProgram.id;
  await assert.rejects(fail('programs','POST',{...validProgram,name:'Unsaved'}),/Storage full/);
  assert.ok(!(await api('data')).programs.some(p=>p.name==='Unsaved'));
});
