import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdtemp,rm} from 'node:fs/promises';
import {join,resolve,sep} from 'node:path';
import {tmpdir} from 'node:os';
test('live tracker persists journal history with authenticated ownership and leaves assigned flow intact',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'iron-heart-tracker-'));
  const child=spawn(process.execPath,['server/index.mjs','--test-server'],{env:{...process.env,PORT:'4191',DEMO_MODE:'true',DB_PATH:join(dir,'test.sqlite'),AI_ENABLED:'false'},stdio:['ignore','pipe','pipe']});
  let output='';child.stdout.on('data',c=>output+=c);child.stderr.on('data',c=>output+=c);
  t.after(async()=>{if(child.exitCode===null){const exit=once(child,'exit');child.kill();await exit;}assert.ok(resolve(dir).startsWith(resolve(tmpdir())+sep));await rm(dir,{recursive:true,force:true});});
  for(let i=0;i<100&&!output.includes('Iron Heart Strength:');i++)await new Promise(r=>setTimeout(r,50));assert.ok(output.includes('Iron Heart Strength:'),output);
  const request=async(path,method='GET',body,token)=>{const r=await fetch('http://localhost:4191/api/'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
  const health=await request('health');assert.equal(health.status,200);assert.equal(health.data.service,'iron-heart');assert.equal(health.data.aiAvailable,false);assert.ok(!JSON.stringify(health.data).includes('API_KEY'));
  const cors=await fetch('http://localhost:4191/api/health',{headers:{Origin:'http://localhost'}});assert.equal(cors.headers.get('access-control-allow-origin'),'http://localhost');
  const input={sessionName:'Journal bench',workoutDate:'2026-10-03',notes:'Independent',exercises:[{exerciseId:'bench',sets:[{reps:5,load:200,rpe:8},{reps:5,load:200,rpe:null}]}]};
  assert.equal((await request('tracker','POST',input)).status,401);
  const coach=(await request('demo','POST',{role:'coach',native:true})).data.token,athlete=(await request('demo','POST',{role:'athlete',native:true})).data.token;
  assert.equal((await request('tracker','POST',input,coach)).status,403);
  const before=(await request('data','GET',null,athlete)).data;
  for(const a of before.assignments)assert.equal((await request('delete','POST',{kind:'assignment',id:a.id},coach)).status,200);
  assert.equal((await request('data','GET',null,athlete)).data.assignments.length,0);
  const saved=await request('tracker','POST',input,athlete);assert.equal(saved.status,200);assert.equal(saved.data.source,'tracker');assert.equal(saved.data.assignmentId,undefined);assert.equal(saved.data.athleteId,'jordan');assert.equal(saved.data.exercises[0].target,undefined);
  assert.deepEqual((await request('data','GET',null,athlete)).data.logs,[saved.data]);
  assert.equal((await request('tracker','POST',{...input,athleteId:'maya'},athlete)).status,400);
  assert.equal((await request('tracker','POST',{...input,exercises:[{exerciseId:'bench',sets:[{reps:5,load:'200'}]}]},athlete)).status,400);
  const workspace=(await request('data','GET',null,coach)).data;
  const assignment=(await request('assign','POST',{programId:workspace.programs[0].id,athleteId:'jordan',startDate:'2026-10-05'},coach)).data;
  const recs=(await request(`recommendations?id=${assignment.id}&week=1`,'GET',null,coach)).data;
  await request('tracker','POST',input,athlete);
  assert.deepEqual((await request(`recommendations?id=${assignment.id}&week=1`,'GET',null,coach)).data,recs);
  const session=assignment.plan[0].sessions[0];
  const planned={assignmentId:assignment.id,week:1,session:0,readiness:4,pain:false,notes:'Planned',exercises:session.exercises.map(e=>({exerciseId:e.exerciseId,sets:Array.from({length:e.sets},()=>({load:e.load,reps:e.reps,rpe:7}))}))};
  assert.equal((await request('log','POST',planned,athlete)).status,200);assert.equal((await request('log','POST',planned,athlete)).status,409);
  const history=(await request('data','GET',null,athlete)).data.logs;assert.equal(history.filter(l=>l.source==='tracker').length,2);assert.equal(history.filter(l=>l.assignmentId===assignment.id).length,1);
  assert.equal((await request('delete','POST',{kind:'log',id:saved.data.id},athlete)).status,200);
});
