import {createRequire} from 'node:module';
import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {once} from 'node:events';import {mkdtemp,rm,mkdir} from 'node:fs/promises';import {join,resolve,sep} from 'node:path';import {tmpdir} from 'node:os';
import {reviewScan} from '../../shared/scan-workout.mjs';import {exercises} from '../../server/seed.mjs';import {missingTrackingExercises} from '../../shared/tracking.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
test('360px Android-sized scanned prescription: target/actual, running pace, optional metrics, recovery and history',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'ih-cardio-scan-'));const server=spawn(process.execPath,['server/index.mjs','--test-server'],{env:{...process.env,PORT:'4199',HOST:'127.0.0.1',DEMO_MODE:'true',DB_PATH:join(dir,'test.sqlite'),AI_ENABLED:'false'},stdio:['ignore','pipe','pipe']});let output='',browser;server.stdout.on('data',c=>output+=c);server.stderr.on('data',c=>output+=c);
 t.after(async()=>{await browser?.close();if(server.exitCode===null){const done=once(server,'exit');server.kill();await done;}assert.ok(resolve(dir).startsWith(resolve(tmpdir())+sep));await rm(dir,{recursive:true,force:true});});
 for(let i=0;i<100&&!output.includes('Iron Heart Strength:');i++)await new Promise(r=>setTimeout(r,50));assert.match(output,/Iron Heart Strength:/);
 browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE});const context=await browser.newContext({viewport:{width:360,height:800}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.request.post('http://127.0.0.1:4199/api/demo',{data:{role:'athlete'}});await page.goto('http://127.0.0.1:4199');await page.getByRole('navigation',{name:'Athlete navigation'}).getByRole('button',{name:'Log',exact:true}).click();
 const draft=reviewScan({sessionName:'Scanned Running Intervals',notes:'',warnings:[],exercises:[{exerciseName:'Outdoor Running',entryKind:'prescribed',blocks:[],complex:[],intervals:[{rounds:2,work:{distance:1000,distanceUnit:'m',paceSeconds:300,paceUnit:'km',rpe:7},recovery:{durationSeconds:60}}]}]},[...exercises,...missingTrackingExercises(exercises)]);
 await page.route('**/api/ai/workout-scan',route=>route.fulfill({json:draft}));await page.getByLabel('Journal photo').setInputFiles({name:'sample.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jv+0AAAAASUVORK5CYII=','base64')});await page.getByRole('button',{name:'Scan and review'}).click();
 await page.getByRole('heading',{name:'Review Workout'}).waitFor();const rows=page.locator('.cardio-interval');assert.equal(await rows.count(),2);const first=rows.first();assert.match(await first.locator('.interval-target').innerText(),/5:00.*1000 m/);assert.equal(await first.getByLabel('Distance',{exact:true}).inputValue(),'');
 await first.getByLabel('Distance',{exact:true}).fill('1000');await first.getByLabel('Duration (M:SS)',{exact:true}).fill('5:10');assert.equal(await first.getByLabel('Pace (M:SS / km)',{exact:true}).inputValue(),'5:10');await first.getByLabel('Pace unit').selectOption('mi');assert.equal(await first.getByLabel('Pace (M:SS / mi)',{exact:true}).inputValue(),'8:19');await first.getByLabel('Distance unit').selectOption('km');assert.equal(await first.getByLabel('Distance',{exact:true}).inputValue(),'1');
 await first.locator('summary').click();await first.getByLabel('Power (W)').fill('220');await first.getByLabel('Cadence (steps/min)').fill('170');await first.getByLabel('Calories',{exact:true}).fill('60');await first.getByLabel('RPE (optional)').fill('8');await first.getByLabel('Actual recovery (M:SS, optional)').fill('1:10');
 await rows.nth(1).getByRole('button',{name:'Copy previous actual results'}).click();await rows.nth(1).getByRole('checkbox').check();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await mkdir('output/qa',{recursive:true});await page.screenshot({path:'output/qa/cardio-intervals-360.png',fullPage:true});
 await page.getByRole('checkbox',{name:'I reviewed and corrected this workout.'}).check();await page.getByRole('button',{name:'Save to Journal'}).click();await page.getByText('Journal workout saved',{exact:true}).waitFor();
 await page.reload();const data=await (await page.request.get('http://127.0.0.1:4199/api/data')).json(),log=data.logs.find(l=>l.sessionName==='Scanned Running Intervals');assert.ok(log);const e=log.exercises[0];assert.equal(e.sets[0].watts,220);assert.equal(e.sets[0].durationSeconds,310);assert.equal(e.sets[0].recoverySeconds,70);assert.equal(e.target.metrics.paceSeconds,300);assert.equal(e.target.intervals[0].recovery.durationSeconds,60);assert.equal(e.sets[1].recoverySeconds,undefined);assert.deepEqual(errors,[]);await context.close();
});
