import {SCHEMA_VERSION,LOAD_MODE,EFFORT_MODE,LOAD_UNIT,DRAFT_STATUS,REFERENCE_TYPE} from './contract.mjs';
export const FIXTURE_REQUIREMENTS=Object.freeze({trainingDaysPerWeek:4,exerciseFrequency:{bench:2,squat:2,deadlift:1},maxSessionMinutes:75,primaryExerciseIds:['bench','squat','deadlift']});
const names={bench:'Barbell Bench Press',squat:'Barbell Back Squat',deadlift:'Conventional Deadlift',row:'Bent-over Barbell Row',pullup:'Pull-up',plank:'Forearm Plank'};
const exercise=(exerciseId,main=false)=>({exerciseId,exerciseName:names[exerciseId],sets:3,reps:main?5:8,load:null,loadMode:LOAD_MODE.ATHLETE_SELECTED,loadUnit:LOAD_UNIT.LBS,percent1RM:null,reference1RM:null,effortMode:main?EFFORT_MODE.RPE:EFFORT_MODE.NONE,rpe:main?8:null,rir:null,rest:main?180:90,tempo:null,increment:2.5,notes:'',progressionInstructions:main?'Coach reviews completed reps and effort before changing next week’s targets.':''});
export function createFixture(kind='valid'){
  const sessions=[
    {name:'Upper strength A',day:1,exercises:[exercise('bench',true),exercise('row')]},
    {name:'Lower strength A',day:2,exercises:[exercise('squat',true),exercise('deadlift',true)]},
    {name:'Upper strength B',day:4,exercises:[exercise('bench',true),{...exercise('pullup'),loadMode:LOAD_MODE.BODYWEIGHT}]},
    {name:'Lower strength B',day:5,exercises:[exercise('squat',true),{...exercise('plank'),loadMode:LOAD_MODE.BODYWEIGHT,notes:'Each rep is one controlled breath.'}]}
  ].map(s=>({...s,maxDurationMinutes:75,coachNotes:''}));
  const draft={schemaVersion:SCHEMA_VERSION,status:DRAFT_STATUS.DRAFT,athleteId:null,sourceProgramId:null,
    originalRequest:'Create a 4-day strength program for an intermediate athlete. Bench twice per week, squat twice per week, deadlift once per week. Keep sessions under 75 minutes. Use RPE for the main lifts and standard sets/reps for accessories. Coach selected a 4-week block for this test fixture.',
    assumptions:[],questions:[],validationFindings:[],program:{name:'Intermediate Strength · Review Sample',goal:'Build strength',description:'Fixture data, not generated by an AI provider.',weeks:4,coachNotes:'Review starting targets for the individual athlete.',progressionInstructions:'Keep this draft’s targets until the coach explicitly reviews progression.',plan:Array.from({length:4},(_,i)=>({week:i+1,sessions:structuredClone(sessions)}))}};
  const e=draft.program.plan[0].sessions[0].exercises[0];
  if(kind==='issues'){
    e.rpe=12;e.tempo='3-X-1';
    draft.program.plan[0].sessions[0].exercises[1].exerciseId=null;
    draft.program.plan[0].sessions[0].exercises[1].exerciseName='Chest-supported row';
    draft.program.plan[0].sessions[2].exercises[0]=exercise('row');
    draft.assumptions=['Available equipment and athlete training history have not been confirmed.'];
  }
  if(kind==='percentage')Object.assign(e,{loadMode:LOAD_MODE.PERCENTAGE,percent1RM:75,reference1RM:{exerciseId:'bench',value:225,unit:LOAD_UNIT.LBS,type:REFERENCE_TYPE.COACH_ENTERED,date:'2026-09-20'}});
  return draft;
}
