import {MODALITIES} from '../program-schedule.mjs';
// Versioned Iron Heart guidance slots. Future rule packs can extend this registry.
export const PROGRAMMING_RULES_VERSION=1;
export const OPTION_FIELDS={
 strength:[['experience','Experience level'],['primaryLifts','Primary lifts'],['setsReps','Sets / reps preferences'],['effort','%1RM / RPE / RIR'],['progression','Progression preference'],['accessories','Accessories'],['deload','Deload preference']],
 hypertrophy:[['split','Training split'],['emphasis','Muscle-group emphasis'],['frequency','Muscle frequency'],['volume','Weekly volume / minimum effective dose'],['repRange','Rep ranges'],['effort','RIR / RPE'],['progression','Progression style'],['deload','Deload preference'],['equipment','Available equipment']],
 running:[['event','Goal / event (Couch-to-5K, 5K, marathon…)'],['ability','Current ability / weekly mileage'],['recentPerformance','Recent race / time trial (distance + time + date)'],['easy','Easy / aerobic work'],['threshold','Threshold work'],['intervals','VO2 / intervals'],['speed','Speed / repetitions'],['longRun','Long run']],
 metcon:[['scoreType','Scoring (For Time, AMRAP, EMOM…)'],['workRest','Duration / work-rest'],['movements','Movement selection'],['equipment','Equipment'],['stimulus','Intended stimulus']],
 hybrid:[['combination','Modalities and days (e.g. strength 4 + running 2)'],['priorities','Goals for each modality'],['recentPerformance','Recent race / time trial if running'],['equipment','Equipment'],['interaction','Explicit changes between modalities (optional)']]
};
export function validateProgrammingOptions(value){if(value===undefined)return null;if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(k=>!['version','modality','options'].includes(k))||value.version!==1||!MODALITIES.includes(value.modality))throw Error('Choose a valid programming modality.');const opts=value.options||{};const allowed=OPTION_FIELDS[value.modality].map(([k])=>k);if(!opts||typeof opts!=='object'||Array.isArray(opts)||Object.keys(opts).some(k=>!allowed.includes(k)||typeof opts[k]!=='string'||opts[k].length>400))throw Error('Invalid modality-specific programming options.');return {version:1,modality:value.modality,options:{...opts}};}
export function methodologyContext(programming){if(!programming)return null;return {rulesVersion:PROGRAMMING_RULES_VERSION,programming,principles:['Use the coach request and structured preferences together; ask about unresolved conflicts.','Only explicit coach requirements authorize changes between modalities.','Use recent race/time-trial results for running paces when supplied; otherwise state assumptions or ask questions.','Use Iron Heart rules, not proprietary or cloned coach programs.','Return the existing structured draft contract. Coach approval is mandatory.']};}
