import React,{useEffect,useState,useRef} from 'react';
import {Sparkles,LoaderCircle} from 'lucide-react';
import {PROGRAM_LENGTHS} from '../shared/ai/contract.mjs';
import {MODALITIES,MODALITY_NAMES} from '../shared/program-schedule.mjs';
import {OPTION_FIELDS} from '../shared/ai/programming-options.mjs';
const example='Create a 6-week strength block for an intermediate athlete. Train 4 days per week. Bench twice per week, squat twice per week, and deadlift once per week. Main lifts should use RPE. Accessories should generally use RIR. Keep sessions around 75 minutes.';
export default function AIProgramBuilder({request,athletes,exercises,onGenerated,seed,full}){
  const [prompt,setPrompt]=useState(''),[athleteId,setAthleteId]=useState(''),[requirements,setRequirements]=useState({}),[status,setStatus]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const alive=useRef(true);
  const [modality,setModality]=useState('strength'),[options,setOptions]=useState({});
  const checkStatus=()=>request('ai/status').then(value=>{if(alive.current)setStatus(value);}).catch(e=>{if(alive.current)setStatus({available:false,reason:e.message||'AI server unavailable. Check the computer server and Wi-Fi connection.'});});
  useEffect(()=>{alive.current=true;checkStatus();return()=>{alive.current=false;};},[]);
  useEffect(()=>{if(seed){setPrompt(seed.draft.originalRequest);setAthleteId(seed.draft.athleteId||'');setRequirements(seed.requirements||{});setModality(seed.programming?.modality||'strength');setOptions(seed.programming?.options||{});setError('');}},[seed]);
  const change=(key,value)=>setRequirements(r=>{const next={...r};if(value==='')delete next[key];else next[key]=Number(value);return next;});
  const frequency=(id,value)=>setRequirements(r=>{const next={...r,exerciseFrequency:{...r.exerciseFrequency}};if(value==='')delete next.exerciseFrequency[id];else next.exerciseFrequency[id]=Number(value);return next;});
  const generate=async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=await request('ai/program-draft','POST',{request:prompt,athleteId:athleteId||null,requirements,programming:{version:1,modality,options}});if(alive.current)onGenerated(result);}catch(e){if(alive.current)setError(e.message);}finally{if(alive.current)setBusy(false);}};
  return <div className="ai-builder"><div className="page-heading"><div><div className="eyebrow">IRON HEART · COACH-LED AI</div><h1>AI Program Builder</h1><p>Describe the training. Review every prescription before it becomes a program.</p></div><Sparkles size={28}/></div>
    <section className="panel"><p className="ai-help">Generation creates an unsaved draft. Approval, saving, and athlete assignment are separate actions. Earlier drafts stay available in AI Draft Review until you refresh or sign out.</p>
      {status?.available&&<p className="info-banner" role="status">AI Server: Connected · Ready to generate a review draft</p>}
      {status&&!status.available&&<div className="info-banner"><p>{status.reason}</p><button type="button" className="text-button" onClick={checkStatus}>Check connection</button></div>}
      <form onSubmit={generate}><fieldset disabled={busy} className="ai-review-controls"><h2>What are you building?</h2><div className="modality-selector" role="group" aria-label="Program type">{MODALITIES.map(m=><button type="button" key={m} aria-pressed={modality===m} onClick={()=>{setModality(m);setOptions({});}}><strong>{MODALITY_NAMES[m]}</strong><small>{m==='hybrid'?'Combine training intentionally':m==='running'?'Paces, intervals & endurance':m==='metcon'?'Compact conditioning blocks':m==='hypertrophy'?'Volume, frequency & growth':'Lifts, effort & progression'}</small></button>)}</div><label className="field"><span>Tell Iron Heart what you want</span><textarea aria-label="Your coaching request" className="ai-prompt" required minLength={10} maxLength={2000} rows={6} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={example}/></label><div className="row spread"><small className="muted">{prompt.length}/2000 characters</small><button className="text-button" type="button" onClick={()=>{setModality('strength');setOptions({});setPrompt(example);setRequirements({programWeeks:6,trainingDaysPerWeek:4,maxSessionMinutes:75,exerciseFrequency:Object.fromEntries(['bench','squat','deadlift'].filter(id=>exercises.some(e=>e.id===id)).map(id=>[id,id==='deadlift'?1:2])),primaryExerciseIds:['bench','squat','deadlift'].filter(id=>exercises.some(e=>e.id===id))});}}>Use example request</button></div><details className="ai-builder-checks"><summary>{MODALITY_NAMES[modality]} preferences · optional</summary><p className="ai-help">These supplement your request. Every prescription still needs your review. Hybrid does not automatically change another modality.</p><div className="form-grid">{OPTION_FIELDS[modality].map(([k,label])=><label className="field" key={k}><span>{label}</span><input aria-label={label} maxLength={400} value={options[k]||''} onChange={e=>setOptions(o=>({...o,[k]:e.target.value}))}/></label>)}</div></details>
      <label className="field"><span>Athlete context (optional)</span><select aria-label="Athlete context" value={athleteId} onChange={e=>setAthleteId(e.target.value)}><option value="">No athlete selected</option>{athletes.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><p className="ai-help">The server sends your request, the exercise library, confirmed checks below, and the selected athlete’s sport only. Names, contact details, workout history, readiness, and pain records are not sent in v1. Do not put passwords or API keys in the request.</p>
      <details className="ai-builder-checks"><summary>Confirmed requirements · independent checks</summary><p className="ai-help">Set these when you want Iron Heart to check them independently. These checks take priority if your request conflicts. Other details in your request still need your review.</p><div className="form-grid">
        <label className="field"><span>Weeks</span><select aria-label="Confirmed weeks" value={requirements.programWeeks??''} onChange={e=>change('programWeeks',e.target.value)}><option value="">Not confirmed</option>{PROGRAM_LENGTHS.map(w=><option key={w} value={w}>{w}</option>)}</select></label>
        {[["trainingDaysPerWeek","Days per week",1,7],["maxSessionMinutes","Session minutes",1,240]].map(([key,label,min,max])=><label className="field" key={key}><span>{label}</span><input type="number" min={min} max={max} value={requirements[key]??''} onChange={e=>change(key,e.target.value)} placeholder="Not confirmed"/></label>)}
        {['bench','squat','deadlift'].filter(id=>exercises.some(e=>e.id===id)).map(id=><label className="field" key={id}><span>{exercises.find(e=>e.id===id).name} · days/week</span><input type="number" min="0" max="7" value={requirements.exerciseFrequency?.[id]??''} onChange={e=>frequency(id,e.target.value)} placeholder="Not confirmed"/></label>)}
      </div><label className="checkbox-field"><input type="checkbox" checked={!!requirements.primaryExerciseIds?.length} onChange={e=>setRequirements(r=>({...r,primaryExerciseIds:e.target.checked?['bench','squat','deadlift'].filter(id=>exercises.some(ex=>ex.id===id)):[]}))}/>Check RPE on bench, squat and deadlift</label><label className="field"><span>Unavailable library equipment</span><select aria-label="Unavailable library equipment" multiple value={requirements.unavailableEquipment||[]} onChange={e=>setRequirements(r=>({...r,unavailableEquipment:[...e.target.selectedOptions].map(o=>o.value)}))}>{[...new Set(exercises.map(e=>e.equipment))].map(item=><option key={item}>{item}</option>)}</select></label></details>
      {seed&&<p className="ai-help">Regeneration opens a separate draft. The previous draft and its approval remain unchanged.</p>}
      {full&&<p className="error">Ten drafts are open. Save the programs you need before refreshing to begin a new review session.</p>}
      {error&&<p className="error" role="alert">{error}</p>}
      <button className="btn" disabled={busy||!status?.available||full||prompt.trim().length<10}><Sparkles size={18}/>{seed?'Regenerate Draft':'Generate Draft'}</button>
      </fieldset></form>
      {busy&&<div className="ai-generating" role="status"><LoaderCircle size={23}/><div><strong>Building your program…</strong><p>Generating the weekly structure and checking the returned prescriptions. This may take a few minutes. Nothing has been saved.</p></div></div>}
    </section>
  </div>;
}
