import {cardioPrescription} from '../shared/cardio-prescriptions.mjs';
import React,{useState} from 'react';
import {prescribedSets,initialActualLoad,prescriptionText} from '../shared/prescriptions.mjs';
import CardioMetrics from './CardioMetrics.jsx';
import {MetconSummary,MetconScoreEditor} from './WorkoutBlocks.jsx';
export default function AssignedWorkout({modal,exercise,exercises,busy,onSave,onVideo}){
 const original=modal.assignment.plan[modal.week-1].sessions[modal.session];
 const s={...original,exercises:original.exercises.map(e=>cardioPrescription(e,exercise(e.exerciseId))||e)};
 const [entries,setEntries]=useState(s.exercises.map(e=>({exerciseId:e.exerciseId,sets:e.trackingType&&e.trackingType!=='strength'?Array.from({length:e.intervalCount||1},()=>({distanceUnit:e.metrics?.distanceUnit||'m'})):prescribedSets(e).map(t=>({load:initialActualLoad(t)??'',loadUnit:t.loadUnit,reps:'',rpe:''}))})));
 const [scores,setScores]=useState({}),[readiness,setReadiness]=useState(3),[pain,setPain]=useState(false);
 const edit=(i,j,patch)=>setEntries(old=>old.map((e,n)=>n===i?{...e,sets:e.sets.map((v,k)=>k===j?{...v,...patch}:v)}:e));
 const blocks=s.blocks||[{id:'legacy',type:'Strength',exerciseIndexes:s.exercises.map((_,i)=>i)}];
 return <form className="dialog-body" onSubmit={e=>{e.preventDefault();onSave({assignmentId:modal.assignment.id,week:modal.week,session:modal.session,exercises:entries.map(e=>({...e,sets:e.sets.map(v=>({...v,...('rpe' in v?{rpe:v.rpe===''?null:v.rpe}:{})}))})),...(s.blocks?{blockResults:s.blocks.filter(b=>b.type==='Metcon').map(b=>({blockId:b.id,score:scores[b.id]||{}}))}:{}),readiness,pain,notes:new FormData(e.target).get('notes')});}}><h3>{s.name}</h3>{s.coachNotes&&<p>{s.coachNotes}</p>}
 {blocks.map(b=><section key={b.id} className="workout-exercise">{s.blocks&&<h2>{b.type}</h2>}{b.type==='Metcon'?<><MetconSummary metcon={b.metcon}/><MetconScoreEditor exercises={exercises} metcon={b.metcon} score={scores[b.id]||{loadUnit:'lbs'}} onChange={score=>setScores({...scores,[b.id]:score})}/></>:b.exerciseIndexes.map(i=>{const e=s.exercises[i];return <section key={i} className="workout-exercise"><div className="row spread"><h3>{exercise(e.exerciseId).name}</h3><button type="button" className="btn secondary" onClick={()=>onVideo(exercise(e.exerciseId))}>Video</button></div><p>Target: {prescriptionText(e)}</p>{e.notes&&<p>{e.notes}</p>}{e.progressionInstructions&&<p>{e.progressionInstructions}</p>}{e.trackingType&&e.trackingType!=='strength'?<>{entries[i].sets.map((v,j)=><div className="cardio-interval" key={j}><h4>{entries[i].sets.length>1?`Interval ${j+1}`:'Completed effort'}</h4><CardioMetrics type={e.trackingType} value={v} onChange={v=>edit(i,j,v)}/></div>)}</>:entries[i].sets.map((set,j)=><div className="metric-grid" key={j}><strong>Set {j+1}</strong>{[['load',0,1200,.25],['reps',0,100,1],['rpe',1,10,.5]].map(([k,min,max,step])=><label className="field" key={k}><span>{k==='load'?`Actual load (${set.loadUnit})`:k.toUpperCase()}</span><input type="number" min={min} max={max} step={step} required={k!=='rpe'||prescribedSets(e)[j].effortMode==='rpe'} value={set[k]} onChange={ev=>edit(i,j,{[k]:ev.target.value===''?'':Number(ev.target.value)})}/></label>)}</div>)}</section>;})}</section>)}
 <label className="field"><span>Readiness</span><select value={readiness} onChange={e=>setReadiness(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label className="checkbox-field"><input type="checkbox" checked={pain} onChange={e=>setPain(e.target.checked)}/>I experienced pain</label><label className="field"><span>Feedback for coach</span><textarea name="notes" maxLength={2000}/></label><button className="btn" disabled={busy}>{busy?'Saving…':'Complete workout'}</button></form>;
}
