import React,{useState} from 'react';
import {cardioStats} from '../shared/cardio-stats.mjs';
import {metconPerformances,metconStats} from '../shared/metcon-stats.mjs';
import {scoreText} from '../shared/workout-blocks.mjs';
import {formatTime} from '../shared/time.mjs';
const n=v=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
function Chart({points,label,valueText,onClick}){const max=Math.max(1,...points.map(p=>p.value));return <section className="panel volume-chart"><h3>{label}</h3>{points.length?<div className="volume-bars">{points.slice(-24).map((p,i)=><button type="button" className="volume-bar" key={i} onClick={()=>onClick?.(p)} aria-label={`${p.date}: ${valueText(p)}`}><span>{valueText(p)}</span><span className="volume-bar-track"><span style={{height:`${Math.max(2,p.value/max*100)}%`}}/></span><small>{p.date}</small></button>)}</div>:<p>No comparable measurements yet.</p>}</section>;}
export function CardioProgress({data,exercise,athlete,onSession}){
 const [period,setPeriod]=useState('sessions'),[unit,setUnit]=useState('mi');
 const s=cardioStats(data.logs,exercise,athlete),swim=s.type==='swimming',erg=s.type==='erg',bike=s.type==='cycling';
 const base=erg?500:swim?(unit==='yd'?91.44:100):unit==='km'?1000:1609.344;
 const speedLabel=erg?'M:SS / 500 m':swim?`M:SS / 100 ${unit==='yd'?'yd':'m'}`:bike?'mph':`M:SS / ${unit==='km'?'km':'mi'}`;
 const performance=v=>v==null?'—':s.metric==='speed'?(bike?`${n(v/.44704)} mph`:`${formatTime(base/v)} ${speedLabel.replace('M:SS','')}`):`${n(v)} ${s.metric==='watts'?'W':s.metric==='stepRate'?'steps/min':s.metric==='floorRate'?'floors/min':'cal'}`;
 const recent=s.latest,points=period==='sessions'?s.comparable.map(r=>({...r,value:r[s.metric]})):s[period];
 return <><div className="panel"><h2>{exercise.name} · Cardio performance</h2><p>{s.status}</p><label className="field"><span>Display units</span><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="mi">Miles / yards</option><option value="km">Kilometers / meters</option>{swim&&<option value="yd">Swim yards</option>}</select></label><p>Comparisons use the latest distance (within 0.5%) or fixed duration (within one second), with matching interval and resistance settings. Higher normalized speed/power indicates improvement; time alone is not ranked.</p></div><div className="volume-cards">{[['Sessions',s.sessions.length],['Total distance',`${n(s.totals.meters/(unit==='km'?1000:unit==='yd'?.9144:1609.344))} ${unit}`],['Total duration',formatTime(s.totals.seconds)],['Average comparable performance',performance(s.average)],['Latest performance',performance(recent?.[s.metric])],['Best comparable performance',performance(s.best?.[s.metric])],['Change vs previous',s.changePercent==null?'—':`${n(s.changePercent)}%`],['Change vs baseline',s.baselineChange==null?'—':`${n(s.baselineChange)}%`],['Latest power',`${n(recent?.watts)} W`],['Latest cadence',`${n(recent?.cadence)} RPM`]].map(([t,v])=><div className="panel" key={t}><span>{t}</span><strong>{v}</strong></div>)}</div><label className="field"><span>Trend period</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="sessions">Sessions</option><option value="weeks">Weeks</option><option value="months">Months</option></select></label><Chart label="Comparable performance trend" points={points} valueText={p=>performance(p.value)} onClick={p=>p.id&&onSession(data.logs.find(l=>l.id===p.id))}/><section className="panel"><h3>Personal bests by distance</h3>{s.distanceBests.map((r,i)=><p key={i}>{n(r.meters)} m · {formatTime(r.seconds)} · {r.date}</p>)}<h3>Distance in a fixed duration</h3>{s.fixedDurationBests.map((r,i)=><p key={i}>{formatTime(r.seconds)} · {n(r.meters)} m · {r.date}</p>)}</section><section className="panel"><h3>Session history</h3>{s.sessions.slice().reverse().map(r=><button className="history-row" key={r.id} onClick={()=>onSession(data.logs.find(l=>l.id===r.id))}><span>{r.date} · {r.name}</span><strong>{n(r.meters)} m · {formatTime(r.seconds)||'—'}{r.speed?` · ${bike?n(r.speed/.44704)+' mph':formatTime(base/r.speed)+' '+speedLabel.replace('M:SS','')}`:''}</strong></button>)}</section></>;
}
export function MetconProgress({data,athlete,onSession}){
 const all=metconPerformances(data.logs,athlete),options=[...new Map(all.map(r=>[r.key,r.metcon.name])).entries()];
 const [selected,setSelected]=useState(''),[rx,setRx]=useState('RX');const key=options.some(([k])=>k===selected)?selected:options[0]?.[0];
 const s=metconStats(data.logs,athlete,key,rx);
 return <><section className="panel"><h2>Metcon benchmarks</h2><div className="form-grid"><label className="field"><span>Repeated workout</span><select value={key||''} onChange={e=>setSelected(e.target.value)}>{options.map(([k,t],i)=><option key={k} value={k}>{t} · variation {i+1}</option>)}</select></label><label className="field"><span>Division</span><select value={rx} onChange={e=>setRx(e.target.value)}><option>RX</option><option>Scaled</option><option>Modified</option></select></label></div><p>{s.status}{s.improvement!=null&&s.latest?.score.timeSeconds!=null?` · ${formatTime(Math.abs(s.improvement))} ${s.improvement>=0?'faster':'slower'} than previous`:null}</p><p>Only identical movement order, targets, rep schemes, duration, cap and instructions are compared. RX and scaled scores remain separate. Scaled notes and actual loads must also match.</p></section><div className="volume-cards">{[['Best',s.best],['Previous',s.previous],['Latest',s.latest]].map(([t,r])=><div className="panel" key={t}><span>{t}</span><strong>{r?scoreText(r.score):'—'}</strong><small>{r?.date}</small></div>)}</div><Chart label="Repeated workout trend" points={s.points} valueText={r=>scoreText(r.score)} onClick={r=>onSession(data.logs.find(l=>l.id===r.id))}/><section className="panel"><h3>Comparable history ({s.sessions.length})</h3>{s.sessions.slice().reverse().map((r,i)=><button className="history-row" key={i} onClick={()=>onSession(data.logs.find(l=>l.id===r.id))}><span>{r.date}</span><strong>{scoreText(r.score)}</strong></button>)}</section></>;
}
