import {CardioProgress,MetconProgress} from './ConditioningProgress.jsx';
import {isCardio} from '../shared/tracking.mjs';
import React,{useState} from 'react';
import {TrendingUp,Trophy,Activity} from 'lucide-react';
import {exerciseVolumeStats} from '../shared/volume-stats.mjs';
import './workout-journal.css';
const amount=n=>n===null||n===undefined?'—':n.toLocaleString(undefined,{maximumFractionDigits:1});
const date=d=>new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'});
export default function ExerciseProgress({data,onSession}){
  const coach=data.user.role==='coach';
  const [athlete,setAthlete]=useState(coach?data.athletes[0]?.id??'':data.user.id),[exercise,setExercise]=useState(data.exercises[0]?.id??''),[unit,setUnit]=useState('lbs');
  const [mode,setMode]=useState('exercise');
  const selectedExercise=data.exercises.find(e=>e.id===exercise),cardio=isCardio(selectedExercise);
  const stats=exerciseVolumeStats(data.logs,exercise,athlete,{unit}),recent=stats.sessions.slice(-12),label=unit==='lbs'?'lb':'kg';
  const title=data.exercises.find(e=>e.id===exercise)?.name||'Exercise';
  const max=Math.max(1,...recent.map(s=>s.volume??0));
  return <section className="volume-page"><div className="page-heading"><div><div className="eyebrow">SEE YOUR WORK ADD UP</div><h1>Exercise Progress</h1><p>Every completed set tells part of the story.</p></div></div>
    <label className="field"><span>Progress type</span><select value={mode} onChange={e=>setMode(e.target.value)}><option value="exercise">Exercise</option><option value="metcon">Metcon benchmarks</option></select></label><div className="panel volume-filters">{coach&&<label className="field"><span>Athlete</span><select value={athlete} onChange={e=>setAthlete(e.target.value)}>{data.athletes.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}<label className="field"><span>Exercise</span><select value={exercise} onChange={e=>setExercise(e.target.value)}>{data.exercises.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label>{!cardio&&mode==='exercise'&&<label className="field"><span>Volume unit</span><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="lbs">Pounds</option><option value="kg">Kilograms</option></select></label>}</div>
    {mode==='metcon'?<MetconProgress data={data} athlete={athlete} onSession={onSession}/>:cardio?<CardioProgress data={data} athlete={athlete} exercise={selectedExercise} onSession={onSession}/>:<>
    <div className="volume-hero"><div className="volume-hero-top"><span><Activity size={18}/> TOTAL VOLUME TODAY</span><span className="badge">{label.toUpperCase()} × REPS</span></div><h2>{title}</h2><strong className="volume-number">{amount(stats.today)}<small>{label}</small></strong><p>{stats.today===null?'No load-based volume recorded today.':'Total recorded external load moved today.'}</p><div className="volume-hero-line"/></div>
    <div className="volume-cards"><div className="panel"><span>Latest session</span><strong>{amount(stats.latest?.volume)} <small>{label}</small></strong><small>{stats.latest?date(stats.latest.date):'No sessions yet'}</small></div><div className="panel"><span>Previous session</span><strong>{amount(stats.previous?.volume)} <small>{label}</small></strong><small>{stats.changePercent===null?'Comparison unavailable':`${stats.changePercent>=0?'+':''}${amount(stats.changePercent)}% latest vs previous`}</small></div><div className="panel"><span><Trophy size={16}/> Best session</span><strong>{amount(stats.best?.volume)} <small>{label}</small></strong><small>{stats.best?date(stats.best.date):'No valid loads yet'}</small></div><div className="panel"><span>This week</span><strong>{amount(stats.weekly)} <small>{label}</small></strong><small>Monday through today</small></div></div>
    <section className="panel volume-chart"><div className="row spread"><h2><TrendingUp size={20}/> Volume trend</h2><small>Last {recent.length} sessions</small></div>{recent.length?<div className="volume-bars" role="group" aria-label="Exercise volume by session">{recent.map(s=><button type="button" className="volume-bar" key={s.id} aria-label={`${date(s.date)}, ${s.name}, ${s.volume===null?'no valid load':amount(s.volume)+' '+label+' volume'}`} onClick={()=>onSession(data.logs.find(l=>l.id===s.id))}><span className="volume-bar-value">{amount(s.volume)}</span><span className="volume-bar-track"><span style={{height:!s.volume?'0%':`${Math.max(2,s.volume/max*100)}%`}}/></span><span>{date(s.date)}</span><small>{s.source==='tracker'?'Journal':'Plan'}</small></button>)}</div>:<p className="journal-empty">Log this exercise in a plan or journal workout to start your trend.</p>}<p className="footnote">Actual reps × recorded load, summed across sets. Units are converted before summing. Missing/invalid loads are excluded; zero external load contributes zero. Timed holds, carries, cardio and mixed-movement complexes are excluded; open their journal entries for time, distance and interval details. Higher volume alone does not measure workout quality.</p></section>
    <section className="panel volume-history"><h2>Recent sessions</h2>{recent.slice().reverse().map(s=><button className="history-row" key={s.id} onClick={()=>onSession(data.logs.find(l=>l.id===s.id))}><div><strong>{s.name}</strong><small>{date(s.date)} · {s.source==='tracker'?'Journal workout':'Assigned workout'} · {s.validSets} sets counted{s.excludedSets?` · ${s.excludedSets} excluded`:''}</small></div><strong>{amount(s.volume)} {label}</strong></button>)}{!recent.length&&<p>No sessions recorded for this exercise.</p>}</section>
  </>}
  </section>;
}
