import React from 'react';
import {Plus,Trash2} from 'lucide-react';
import {LOAD_MODE as L,EFFORT_MODE as E,LOAD_UNIT,REFERENCE_TYPE,parseOptionalNumber} from '../shared/ai/contract.mjs';
import {normalizePrescription,loadText,validatePrescription} from '../shared/prescriptions.mjs';
const Field=({label,children})=><label className="field"><span>{label}</span>{children}</label>;
export {newPrescription} from '../shared/prescriptions.mjs';
export default function PrescriptionEditor({items,exercises,onChange}){
  const change=(i,patch)=>onChange(items.map((old,j)=>{if(i!==j)return old;const next={...normalizePrescription(old),...patch};if(next.loadMode===L.PERCENTAGE)next.load=null;return next;}));
  return <><div className="exercise-editor">{items.map((item,i)=>{
    const e=normalizePrescription(item),label=s=>`${s} exercise ${i+1}`,edit=(k,v)=>change(i,{[k]:v});
    const input=(key,title,min,max,step=1,required=true)=><Field label={title}><input aria-label={label(title)} type="number" min={min} max={max} step={step} required={required} value={e[key]??''} onChange={ev=>edit(key,parseOptionalNumber(ev.target.value))}/></Field>;
    const findings=validatePrescription(e,exercises);
    const reference=e.reference1RM;
    const ref=(key,value)=>edit('reference1RM',{...reference,[key]:value});
    return <div className="editor-row" key={i}>
      <div className="editor-top"><span className="exercise-index">{String.fromCharCode(65+i)}</span><select aria-label={`Exercise ${i+1}`} value={e.exerciseId} onChange={ev=>change(i,{exerciseId:ev.target.value,exerciseName:exercises.find(x=>x.id===ev.target.value)?.name,reference1RM:null})}>{exercises.map(ex=><option key={ex.id} value={ex.id}>{ex.name}</option>)}</select><button type="button" className="icon-button danger" disabled={items.length===1} aria-label={`Remove exercise ${i+1}`} onClick={()=>onChange(items.filter((_,j)=>j!==i))}><Trash2 size={17}/></button></div>
      <div className="target-fields">
        {input('sets','Sets',1,12)}{input('reps','Reps',1,50)}
        <Field label="Loading"><select aria-label={label('Loading')} value={e.loadMode} onChange={ev=>change(i,{loadMode:ev.target.value,load:null,percent1RM:null,reference1RM:null})}>{[[L.FIXED,'Fixed'],[L.PERCENTAGE,'% 1RM'],[L.BODYWEIGHT,'Bodyweight'],[L.ATHLETE_SELECTED,'Athlete selects']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></Field>
        {e.loadMode===L.FIXED&&input('load','Load',0,1200,'any')}
        {e.loadMode===L.PERCENTAGE&&input('percent1RM','% 1RM',1,100,'any')}
        <Field label="Weight unit"><select aria-label={label('Weight unit')} value={e.loadUnit} onChange={ev=>edit('loadUnit',ev.target.value)}>{Object.values(LOAD_UNIT).map(unit=><option key={unit}>{unit}</option>)}</select></Field>
        <Field label="Effort"><select aria-label={label('Effort')} value={e.effortMode} onChange={ev=>change(i,{effortMode:ev.target.value,rpe:null,rir:null})}>{[[E.NONE,'None'],[E.RPE,'RPE'],[E.RIR,'RIR']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></Field>
        {e.effortMode===E.RPE&&input('rpe','Target RPE',1,10,.5)}
        {e.effortMode===E.RIR&&input('rir','Target RIR',0,10,.5)}
        {input('rest','Rest (sec)',0,600,5)}{input('increment',`Step (${e.loadUnit})`,.25,25,.25)}
      </div>
      <details className="prescription-details"><summary>Varied set blocks (optional)</summary><p className="footnote">Each block inherits the loading, effort and rest settings above. Total sets must stay within 12. Automatic progression holds these blocks for coach review.</p>{(e.setBlocks||[]).map((b,j)=><div className="metric-grid" key={j}>{[['sets','Sets'],['reps','Reps'],...(e.loadMode===L.FIXED?[['load','Load']]:[]),...(e.loadMode===L.PERCENTAGE?[['percent1RM','% 1RM']]:[])].map(([k,title])=><Field key={k} label={title}><input type="number" min={k==='load'?0:1} step={k==='load'||k==='percent1RM'?'any':1} value={b[k]??(k==='sets'?b.count:undefined)??''} required onChange={ev=>{const next=e.setBlocks.map((v,n)=>n===j?{...v,[k]:parseOptionalNumber(ev.target.value)}:v);change(i,{setBlocks:next,sets:next.reduce((n,v)=>n+(v.sets??v.count??0),0)});}}/></Field>)}<button type="button" className="btn secondary" onClick={()=>{const next=e.setBlocks.filter((_,n)=>n!==j);change(i,{setBlocks:next.length?next:undefined,sets:next.length?next.reduce((n,b)=>n+(b.sets??b.count),0):e.sets});}}>Delete block</button></div>)}<button type="button" className="btn secondary" disabled={(e.setBlocks?.length||0)>=12} onClick={()=>{const next=[...(e.setBlocks||[]),{sets:1,reps:e.reps,...(e.loadMode===L.FIXED?{load:e.load}:{}),...(e.loadMode===L.PERCENTAGE?{percent1RM:e.percent1RM}:{})}];change(i,{setBlocks:next,sets:next.reduce((n,b)=>n+(b.sets??b.count),0)});}}>+ Add Set Block</button></details>
      {e.loadMode===L.PERCENTAGE&&<div className="prescription-reference"><p className="footnote">{loadText(e)}</p><details><summary>Reference maximum</summary>{!reference?<button type="button" className="text-button" onClick={()=>edit('reference1RM',{exerciseId:e.exerciseId,value:null,unit:e.loadUnit,type:REFERENCE_TYPE.COACH_ENTERED,date:''})}>Add reference maximum</button>:<><div className="form-grid"><Field label="Reference lift"><select aria-label={label('Reference lift')} value={reference.exerciseId} onChange={ev=>ref('exerciseId',ev.target.value)}>{exercises.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Reference maximum"><input aria-label={label('Reference maximum')} type="number" min="0.25" max="1200" step="any" value={reference.value??''} onChange={ev=>ref('value',parseOptionalNumber(ev.target.value))}/></Field><Field label="Reference unit"><select value={reference.unit} onChange={ev=>ref('unit',ev.target.value)}>{Object.values(LOAD_UNIT).map(unit=><option key={unit}>{unit}</option>)}</select></Field><Field label="Reference source"><select value={reference.type} onChange={ev=>ref('type',ev.target.value)}>{Object.values(REFERENCE_TYPE).map(type=><option key={type} value={type}>{type.replaceAll('_',' ')}</option>)}</select></Field><Field label="Reference date"><input type="date" value={reference.date} onChange={ev=>ref('date',ev.target.value)}/></Field></div><button className="text-button" type="button" onClick={()=>edit('reference1RM',null)}>Clear reference maximum</button></>}</details></div>}
      <details className="prescription-details"><summary>Tempo, notes & progression</summary><div className="form-grid"><Field label="Tempo (optional)"><input aria-label={label('Tempo')} placeholder="3-1-X-0" value={e.tempo??''} onChange={ev=>edit('tempo',ev.target.value||null)}/></Field><Field label="Progression instructions"><textarea aria-label={label('Progression instructions')} value={e.progressionInstructions} onChange={ev=>edit('progressionInstructions',ev.target.value)}/></Field></div><input className="notes-input" aria-label={`Coaching notes exercise ${i+1}`} placeholder="Coaching notes…" value={e.notes} onChange={ev=>edit('notes',ev.target.value)}/></details>
      {findings.map((f,j)=><p className={f.severity==='error'?'error':'footnote'} key={j}>{f.message}</p>)}
    </div>;
  })}</div><button type="button" className="btn secondary" disabled={items.length>=15} onClick={()=>onChange([...items,newPrescription(exercises[0]?.id)])}><Plus size={16}/>Add from exercise library</button></>;
}
