import React,{useState} from 'react';
import {Sparkles,Check,ChevronDown} from 'lucide-react';
import {generateBlock,supportsLoadProgression} from '../server/progression.mjs';
import {loadText} from '../shared/prescriptions.mjs';

export default function ProgressionGenerator({sessions,weeks,exercises,onApply,existing=false,initialOptions}){
  const [open,setOpen]=useState(false),[options,setOptions]=useState(initialOptions||{method:'westside',roundTo:5,rules:{}}),[preview,setPreview]=useState(null),[error,setError]=useState('');
  const editRule=(key,change)=>{setOptions({...options,rules:{...options.rules,[key]:{mode:'hold',referenceMax:0,increase:0,...options.rules[key],...change}}});setPreview(null);};
  function update(key,value){setOptions({...options,[key]:Number(value)});setPreview(null);setError('');}
  function build(){try{setPreview(generateBlock(sessions,weeks,options));setError('');}catch(e){setError(e.message);}}
  const name=id=>exercises.find(e=>e.id===id)?.name||'Exercise';
  return <section className="generator">
    <button className="generator-heading" type="button" onClick={()=>setOpen(!open)} aria-expanded={open}><Sparkles size={21}/><span><strong>Generate following weeks</strong><small>Turn Week 1 into a complete progressive training block.</small></span><ChevronDown size={18}/></button>
    {open&&<div className="generator-body"><p><strong>Westside-inspired conjugate planning.</strong> Keep your Week 1 intact and choose a method for each exercise. All generated weeks remain fully editable.</p><div className="generator-options">
      <label className="field"><span>Round weights to (lbs)</span><select value={options.roundTo} onChange={e=>update('roundTo',e.target.value)}>{[.5,1,2.5,5,10].map(n=><option key={n} value={n}>{n} lbs</option>)}</select></label>
    </div><div className="generator-rules">{sessions.flatMap((s,si)=>s.exercises.map((e,ei)=>{const key=`${si}:${ei}:${e.exerciseId}`,rule=options.rules[key]||{mode:'hold',referenceMax:0,increase:0};return <div className="generator-rule" key={key}><div><strong>{name(e.exerciseId)}</strong><small>{s.name}</small></div><label className="field"><span>Training method</span><select aria-label={`Method for ${name(e.exerciseId)} session ${si+1} exercise ${ei+1}`} disabled={!supportsLoadProgression(e)} value={supportsLoadProgression(e)?rule.mode:'hold'} onChange={ev=>editRule(key,{mode:ev.target.value})}><option value="hold">Keep my prescription</option><option value="speed-squat">Dynamic effort · squat wave</option><option value="speed-bench">Dynamic effort · bench wave</option><option value="max">Max effort · coach sets load</option><option value="repetition">Repetition effort · accessories</option></select></label>{rule.mode.startsWith('speed-')&&<label className="field"><span>Reference max (lbs)</span><input aria-label={`Reference max session ${si+1} exercise ${ei+1}`} type="number" min="1" max="1200" step="0.25" value={rule.referenceMax||''} onChange={ev=>editRule(key,{referenceMax:Number(ev.target.value)})}/></label>}{rule.mode==='repetition'&&<label className="field"><span>Coach-selected weekly increase (%)</span><input type="number" min="0" max="5" step="0.5" value={rule.increase} onChange={ev=>editRule(key,{increase:Number(ev.target.value)})}/></label>}</div>}))}</div><p className="footnote">Squat uses repeating 50/55/60% bar-weight waves; bench uses the published 45/50/55% bar-weight component, adapted here without bands or chains. Squat uses the introductory 10/8/6 × 2 wave; bench uses 9 × 3. Week 1 is your unchanged baseline, so set it to the first-wave prescription yourself if desired. Week 4 restarts the wave—not an automatic deload. Coach-select exercise rotations and recovery weeks in the editor. Max-effort loads stay coach-set; accessory increases are your custom choice, not a Westside percentage rule.</p><p className="footnote">Adapted from <a href="https://www.westside-barbell.com/blogs/the-blog/introducing-dynamic-effort-beginners" target="_blank" rel="noreferrer">Westside’s introductory dynamic effort guidance</a> and <a href="https://www.westside-barbell.com/blogs/the-blog/the-wsbb-guide-to-dynamic-effort-training" target="_blank" rel="noreferrer">dynamic effort guide</a>. This is a limited Westside-inspired planning tool, not an official Westside program. Maintain speed and technique; reduce loads when needed.</p>
    <p className="footnote">Automatic load changes support fixed pounds with RPE. Other prescription modes keep their targets; edit their weeks manually.</p><button className="btn secondary" type="button" onClick={build}><Sparkles size={16}/>Preview Weeks 2–{weeks}</button>
    {error&&<p className="error" role="alert">{error}</p>}
    {preview&&<><div className="generated-preview"><table><caption>Review the generated block</caption><thead><tr><th>Week</th><th>Session / exercise</th><th>Sets × reps</th><th>Weight</th></tr></thead><tbody>{preview.map(w=>w.sessions.flatMap((s,si)=>s.exercises.map((e,ei)=><tr key={`${w.week}-${si}-${ei}`} className={w.week===1?'baseline':e.phase==='Deload'?'deload':''}><td>W{w.week}<small>{w.week===1?'Your baseline':e.phase==='Deload'?'Deload':'Build'}</small></td><td><small>{s.name}</small>{name(e.exerciseId)}</td><td>{e.sets} × {e.reps}</td><td>{loadText(e)}</td></tr>)))}</tbody></table></div><p className="footnote">{existing?'Applying replaces your current draft for Weeks 2–'+weeks+'. ':''}Week 1 stays unchanged. Save the program afterward to keep the generated weeks. Existing athlete assignments stay unchanged.</p><button type="button" className="btn" onClick={()=>{onApply(preview,options);setPreview(null);setOpen(false);}}><Check size={17}/>Apply generated weeks</button></>}
    </div>}
  </section>;
}
