import React,{useState} from 'react';
import {validateApiBase,NETWORK_MESSAGE} from '../shared/api-connection.mjs';
export const CONNECTION_KEY='iron-heart-preview-api-url';
export default function ServerConnection(){
 const [url,setUrl]=useState(localStorage.getItem(CONNECTION_KEY)||import.meta.env.VITE_API_BASE_URL||import.meta.env.VITE_API_URL||''),[status,setStatus]=useState('Not checked'),[busy,setBusy]=useState(false);
 async function connect(){setBusy(true);try{const base=validateApiBase(url,{preview:true});if(!base)throw Error('Enter your Iron Heart server address first.');const r=await fetch(base+'/api/health',{signal:AbortSignal.timeout(8000)});const data=await r.json();if(!r.ok||data.service!=='iron-heart')throw Error(NETWORK_MESSAGE);setStatus('AI Server: Connected'+(data.aiAvailable?'':' · AI provider not configured'));}catch(e){setStatus(e.name==='TypeError'||e.name==='TimeoutError'?NETWORK_MESSAGE:e.message);}finally{setBusy(false);}}
 function apply(){try{const base=validateApiBase(url,{preview:true});localStorage.setItem(CONNECTION_KEY,base);location.reload();}catch(e){setStatus(e.message);}}
 return <section className="server-connection"><h3>Phone server connection</h3><p>Use your hosted Iron Heart HTTPS address for shared workout history and live AI. Sign in again after reopening the connected app to reload your server history. Phone-only preview uses a separate history saved on this device; switching modes does not delete either history.</p><label className="field"><span>Iron Heart API address</span><input value={url} onChange={e=>{setUrl(e.target.value);setStatus('Not checked');}} placeholder="https://your-iron-heart-server.onrender.com" autoCapitalize="off" autoCorrect="off"/></label><div className="row"><button type="button" className="btn secondary" disabled={busy} onClick={connect}>{busy?'Checking…':'Test connection'}</button><button type="button" className="btn" onClick={apply}>Use server & sign in</button><button type="button" className="text-button" onClick={()=>{localStorage.removeItem(CONNECTION_KEY);location.reload();}}>Use phone-only preview</button></div><p role="status">{status}</p></section>;
}
