import React,{useState} from 'react';
import {Plus,Trash2,Search,CheckCircle2,Camera} from 'lucide-react';
import {localDateString} from '../shared/workout-tracker.mjs';
import {trackingProfile,FIELDS,MODIFIERS,convertDistance,expandBlocks,complexLabel,exerciseCategory} from '../shared/tracking.mjs';
import './workout-journal.css';
const blank=()=>({count:1,reps:'',load:'',loadUnit:'lbs',rpe:'',rir:'',distanceUnit:'mi'});
const labels={count:'Sets',reps:'Reps',load:'Load',rpe:'RPE (optional)',rir:'RIR (optional)',durationSeconds:'Duration (sec)',distance:'Distance',speedMph:'Speed (mph)',incline:'Incline (%)',level:'Level',paceSeconds:'Pace (sec)'};
export function cleanJournalSet(s){const out={};for(const [k,v] of Object.entries(s))if(!['key','blockIndex'].includes(k))out[k]=['loadUnit','distanceUnit'].includes(k)?v:v===''||v==null?null:Number(v);return out;}
function Metrics({value,type,onChange,grouped=false,complex=false,prefix=''}){
 const fields=[...(grouped?['count']:[]),...FIELDS[type].filter(k=>!(complex&&k==='reps'))];
 const update=(k,v)=>onChange({...value,[k]:v});
 function unit(next){const prev=value.distanceUnit||(type==='carry'?'m':'mi'),out={...value,distanceUnit:next};if(value.distance!==''&&value.distance!=null)out.distance=+convertDistance(Number(value.distance),prev,next).toFixed(6);if(type==='running'&&value.paceSeconds!==''&&value.paceSeconds!=null)out.paceSeconds=+convertDistance(Number(value.paceSeconds),next,prev).toFixed(3);onChange(out);}
 return <div className="metric-grid">{fields.map(k=><label className="field" key={k}><span>{k==='paceSeconds'?(type==='erg'?'Pace (sec / 500 m)':`Pace (sec / ${value.distanceUnit||'mi'})`):labels[k]}</span><input aria-label={`${prefix}${labels[k]}`} type="number" min={k==='count'?1:0} step={['count','reps'].includes(k)?1:'any'} max={k==='count'?30:undefined} required={k==='count'||k==='reps'||(['timed','loadedTimed'].includes(type)&&k==='durationSeconds')} value={value[k]??''} onChange={e=>update(k,e.target.value)}/></label>)}{FIELDS[type].includes('load')&&<label className="field"><span>Load unit</span><select value={value.loadUnit||'lbs'} onChange={e=>update('loadUnit',e.target.value)}><option value="lbs">lb</option><option value="kg">kg</option></select></label>}{FIELDS[type].includes('distance')&&<label className="field"><span>Distance unit</span><select value={value.distanceUnit||(type==='carry'?'m':'mi')} onChange={e=>unit(e.target.value)}><option value="mi">miles</option><option value="km">kilometers</option><option value="m">meters</option></select></label>}</div>;
}
export default function WorkoutTracker({exercises,onSave,busy,request}){
 const [name,setName]=useState(''),[date,setDate]=useState(localDateString()),[notes,setNotes]=useState(''),[search,setSearch]=useState(''),[entries,setEntries]=useState([]),[error,setError]=useState(''),[scanning,setScanning]=useState(false),[review,setReview]=useState(false),[confirmed,setConfirmed]=useState(false),[photo,setPhoto]=useState(null);
 const add=exercise=>setEntries(previous=>[...previous,{key:crypto.randomUUID(),exerciseId:exercise.id,blocks:[{...blank(),distanceUnit:trackingProfile(exercise)==='carry'?'m':'mi'}],complex:[],intervals:[]}]);
 const change=(key,fn)=>{setConfirmed(false);setEntries(previous=>previous.map(e=>e.key===key?fn(e):e));};
 const phase=p=>Object.fromEntries(Object.entries(cleanJournalSet(p)).filter(([k,v])=>v!=null&&!['count','loadUnit'].includes(k)));
 async function submit(event){event.preventDefault();setError('');if(busy||!entries.length||(review&&!confirmed))return;
 try{const saved=await onSave({sessionName:name,workoutDate:date,notes,exercises:entries.map(e=>({exerciseId:e.exerciseId,...(e.individual?{sets:e.sets.map(cleanJournalSet)}:{blocks:e.blocks.map(cleanJournalSet)}),complex:e.complex||[],notes:e.notes||'',intervals:(e.intervals||[]).map(b=>({rounds:Number(b.rounds),work:phase(b.work),recovery:phase(b.recovery)}))}))});if(saved){setEntries([]);setName('');setNotes('');setReview(false);setConfirmed(false);setPhoto(null);}}catch(e){setError(e.message);}}
 async function scan(){if(!photo)return;setScanning(true);setError('');try{const image=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(photo);});const result=await request('ai/workout-scan','POST',{image});setName(result.workout.sessionName);setNotes(result.workout.notes);setEntries(result.workout.exercises.map(e=>({...e,key:crypto.randomUUID(),complex:e.complex||[],intervals:[],blocks:e.blocks.map(b=>({...blank(),...b}))})));setReview(true);setConfirmed(false);setPhoto(null);setError(result.warnings.join(' '));}catch(e){setError(e.message);}finally{setScanning(false);}}
 return <section className="journal-page"><div className="page-heading"><div><div className="eyebrow">YOUR WORK. YOUR RECORD.</div><h1>{review?'Review Workout':'Workout Tracker'}</h1><p>{review?'Correct the interpretation below. Nothing has been saved.':'Strength, complexes, holds and cardio. Record what you completed.'}</p></div></div>
 <section className="panel journal-details"><h2><Camera size={20}/> Scan Workout</h2><p className="footnote">Take or upload a journal photo (JPEG, PNG, WebP; up to 4 MB). It is sent to the configured AI server/provider only when you choose Scan. Review every result before saving.</p><label className="field"><span>Journal photo</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={scanning||entries.length>0} onChange={e=>{const f=e.target.files?.[0];if(f&&f.size>4*1024*1024){setError('Choose an image smaller than 4 MB.');return;}setPhoto(f||null);}}/></label><button className="btn secondary" disabled={!photo||scanning||entries.length>0} onClick={scan}>{scanning?'Reading journal…':'Scan and review'}</button>{entries.length>0&&<small>Finish or remove the current entries before scanning another workout.</small>}</section>
 {error&&<p className="error" role="alert">{error}</p>}
 <form onSubmit={submit}><fieldset disabled={busy||scanning} className="journal-fieldset"><div className="panel journal-details"><div className="form-grid"><label className="field"><span>Workout name</span><input required maxLength={200} value={name} onChange={e=>{setName(e.target.value);setConfirmed(false);}} placeholder="Saturday strength"/></label><label className="field"><span>Workout date</span><input required type="date" value={date} onChange={e=>{setDate(e.target.value);setConfirmed(false);}}/></label></div></div>
 <section className="panel journal-picker"><h2>Add exercises</h2><label className="field"><span><Search size={15}/> Search exercise library</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Bench, Olympic Weightlifting, Cardio…"/></label><div className="journal-results">{exercises.filter(e=>`${e.name} ${e.equipment} ${exerciseCategory(e)}`.toLowerCase().includes(search.toLowerCase())).map(e=><button className="journal-result" type="button" key={e.id} disabled={entries.length>=15} onClick={()=>{add(e);setConfirmed(false);}}><span><strong>{e.name}</strong><small>{exerciseCategory(e)} · {e.equipment}</small></span><Plus size={18}/></button>)}</div></section>
 {entries.map((entry,i)=>{const exercise=exercises.find(e=>e.id===entry.exerciseId),type=trackingProfile(exercise),list=entry.individual?entry.sets:entry.blocks;const updateList=(j,b)=>change(entry.key,x=>({...x,[entry.individual?'sets':'blocks']:list.map((s,n)=>j===n?b:s)}));return <section className="panel journal-exercise" key={entry.key}>
 <div className="row spread"><h2>{exercise?.name||entry.exerciseName||'Choose exercise'}</h2><button className="icon-button danger" type="button" aria-label={`Remove exercise ${i+1}`} onClick={()=>{setEntries(entries.filter(e=>e.key!==entry.key));setConfirmed(false);}}><Trash2 size={18}/></button></div>
 {review&&<label className="field"><span>Correct exercise match</span><select required value={entry.exerciseId||''} onChange={e=>change(entry.key,x=>({...x,exerciseId:e.target.value}))}><option value="">Choose matching exercise</option>{exercises.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>}
 {type==='strength'&&<details className="complex-editor" open={entry.complex?.length?true:undefined}><summary>Variations / exercise complex</summary>{entry.complex?.map((p,j)=><div className="metric-grid" key={j}><label className="field"><span>Reps in complex</span><input type="number" min="1" max="100" required value={p.reps} onChange={e=>change(entry.key,x=>({...x,complex:x.complex.map((c,n)=>n===j?{...c,reps:Number(e.target.value)}:c)}))}/></label><label className="field"><span>Movement</span><select value={p.exerciseId} onChange={e=>change(entry.key,x=>({...x,complex:x.complex.map((c,n)=>n===j?{...c,exerciseId:e.target.value}:c)}))}>{exercises.filter(e=>trackingProfile(e)==='strength').map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label className="field"><span>Modifier</span><select value={p.modifier} onChange={e=>change(entry.key,x=>({...x,complex:x.complex.map((c,n)=>n===j?{...c,modifier:e.target.value}:c)}))}><option value="">Standard</option>{MODIFIERS.map(m=><option key={m}>{m}</option>)}</select></label><button type="button" className="btn secondary" onClick={()=>change(entry.key,x=>({...x,complex:x.complex.filter((_,n)=>n!==j)}))}>Remove movement</button></div>)}<button type="button" className="btn secondary" disabled={entry.complex.length>=10} onClick={()=>change(entry.key,x=>({...x,complex:[...x.complex,{exerciseId:entry.exerciseId,reps:1,modifier:''}]}))}>+ Add movement</button>{entry.complex.length>0&&<p>{complexLabel(entry.complex,exercises)}</p>}</details>}
 {list.map((s,j)=><div className="set-block" key={j}><div className="row spread"><strong>{entry.individual?'Set':'Set block'} {j+1}</strong><button type="button" className="icon-button danger" disabled={list.length===1} aria-label={`Delete block ${i+1}-${j+1}`} onClick={()=>change(entry.key,x=>({...x,[entry.individual?'sets':'blocks']:list.filter((_,n)=>n!==j)}))}><Trash2 size={17}/></button></div><Metrics prefix={`Exercise ${i+1} block ${j+1} `} value={s} type={type} grouped={!entry.individual} complex={entry.complex?.length>0} onChange={b=>updateList(j,b)}/></div>)}
 <div className="row"><button type="button" className="btn secondary" disabled={list.length>=30} onClick={()=>change(entry.key,x=>({...x,[entry.individual?'sets':'blocks']:[...list,blank()]}))}>+ Add {entry.individual?'Set':'Set Block'}</button>{!entry.individual&&<button type="button" className="text-button" onClick={()=>{try{const sets=expandBlocks(entry.blocks.map(b=>({...b,count:Number(b.count)}))).map(({count,blockIndex,...s})=>s);change(entry.key,x=>({...x,individual:true,sets}));}catch(e){setError(e.message);}}}>Edit individual sets</button>}</div>
 {['treadmill','stairs','erg','running'].includes(type)&&<section className="interval-editor"><h3>Intervals (optional)</h3><p className="footnote">Record session totals above. These blocks describe the work and recovery; they are not added again to totals.</p>{entry.intervals.map((b,j)=><div className="set-block" key={j}><label className="field"><span>Rounds</span><input type="number" min="1" max="100" required value={b.rounds} onChange={e=>change(entry.key,x=>({...x,intervals:x.intervals.map((v,n)=>n===j?{...v,rounds:e.target.value}:v)}))}/></label>{['work','recovery'].map(p=><div key={p}><h4>{p==='work'?'Work':'Recovery'}</h4><Metrics value={b[p]} type={type} onChange={v=>change(entry.key,x=>({...x,intervals:x.intervals.map((old,n)=>n===j?{...old,[p]:v}:old)}))}/></div>)}<button type="button" className="btn secondary" onClick={()=>change(entry.key,x=>({...x,intervals:x.intervals.filter((_,n)=>n!==j)}))}>Delete interval</button></div>)}<button type="button" className="btn secondary" disabled={entry.intervals.length>=20} onClick={()=>change(entry.key,x=>({...x,intervals:[...x.intervals,{rounds:1,work:{distanceUnit:'mi'},recovery:{distanceUnit:'mi'}}]}))}>+ Add Interval Block</button></section>}
 <label className="field"><span>Exercise notes / tempo</span><textarea value={entry.notes||''} maxLength={2000} onChange={e=>change(entry.key,x=>({...x,notes:e.target.value}))}/></label></section>;})}
 <div className="panel journal-details"><label className="field"><span>Workout notes</span><textarea maxLength={2000} rows={3} value={notes} onChange={e=>{setNotes(e.target.value);setConfirmed(false);}}/></label><p className="footnote">Load is external weight only. Blank loads are excluded from volume. Holds, carries, cardio and mixed-movement complexes are not counted as traditional rep-based volume.</p>{review&&<label className="checkbox-field"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed and corrected this workout.</label>}<button className="btn" disabled={busy||!entries.length||(review&&!confirmed)}><CheckCircle2 size={18}/>{busy?'Saving…':review?'Save to Journal':'Save journal workout'}</button></div>
 </fieldset></form></section>;
}
